version: "3"

services:
  game:
    image: jhartway99/htmx-flappybird:latest
    network_mode: "host"
    build:
      context: ./
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
