version: "3"

services:
  game:
    image: jhartway99/htmx-flappybird:latest
    network_mode: "host"
    build:
      context: ./
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./app
